### ISSUE TITLE
Latest version no longer Plone 4.x compatbile

### ISSUE THREAD

**Issue by puittenbroek** [plone/Products.PortalTransforms#23]
Products.PortalTransforms > 3.1 is no longer compatible with Plone 4.X due to the following import:

    from Products.CMFPlone.interfaces import IFilterSchema

Which is not available in 4.X, tested up to `4.3.15`. But branches in [CMFPlone](https://github.com/plone/Products.CMFPlone/blob/4.3.x/Products/CMFPlone/interfaces/controlpanel.py) also make this clear.

There should be a warning on pypi page and docs making this clear.

Would be nice if a similar solution was made available for Plone 4.X, now only a evil monkeypatch can safe (my/the) day. Because the `safe_attrs` in 3.0 is not configurable any other way. And I need the a higher version for improved safe_html.

**Comment by mauritsvanrees** [comment]
This is a new feature in Plone 5.1 and is a big change in Products.PortalTransforms. I don't expect that anyone wants to do the work to port this to Plone 4.3. If you really want to, you could make a branch and try it. But that is too big a change to ever land officially in 4.3 (or 5.0).

**Comment by puittenbroek** [comment]
The compatibility should be mentioned in next versions tho.

**Comment by mauritsvanrees** [comment]
I have added a compatibility header in PR #26:

- For Plone 4 and 5.0, use version 2.x.

- For Plone 5.1 and later, use version 3.
